# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: view_ms1_cmds.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='view_ms1_cmds.proto',
  package='pb',
  serialized_pb='\n\x13view_ms1_cmds.proto\x12\x02pb\"\x8a\x01\n\x0eViewMS1Command\x12\x0c\n\x04load\x18\x01 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x02 \x01(\x01\x12\x0e\n\x06min_mz\x18\x03 \x01(\x01\x12\x0e\n\x06max_mz\x18\x04 \x01(\x01\x12\x11\n\tmin_rtime\x18\x05 \x01(\x01\x12\x11\n\tmax_rtime\x18\x06 \x01(\x01\x12\x14\n\x0cwrite_matrix\x18\x07 \x01(\tB\x02H\x01')




_VIEWMS1COMMAND = _descriptor.Descriptor(
  name='ViewMS1Command',
  full_name='pb.ViewMS1Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='load', full_name='pb.ViewMS1Command.load', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bucket', full_name='pb.ViewMS1Command.bucket', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_mz', full_name='pb.ViewMS1Command.min_mz', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_mz', full_name='pb.ViewMS1Command.max_mz', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_rtime', full_name='pb.ViewMS1Command.min_rtime', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_rtime', full_name='pb.ViewMS1Command.max_rtime', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='write_matrix', full_name='pb.ViewMS1Command.write_matrix', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=166,
)

DESCRIPTOR.message_types_by_name['ViewMS1Command'] = _VIEWMS1COMMAND

class ViewMS1Command(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VIEWMS1COMMAND

  # @@protoc_insertion_point(class_scope:pb.ViewMS1Command)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\001')
# @@protoc_insertion_point(module_scope)
